In [17]:
import numpy as np

In [18]:
def needleman_wunsch(seq1, seq2, match=1, mismatch=-1, gap=-1):
    # Инициализация матрицы
    n = len(seq1)
    m = len(seq2)
    score_matrix = [[0 for j in range(m + 1)] for i in range(n + 1)]

    # Заполнение первой строки и столбца (штрафы за пропуски)
    for i in range(1, n + 1):
        score_matrix[i][0] = i * gap
    for j in range(1, m + 1):
        score_matrix[0][j] = j * gap

    # Заполнение матрицы оценок
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            match_score = match if seq1[i - 1] == seq2[j - 1] else mismatch
            score_matrix[i][j] = max(
                score_matrix[i - 1][j - 1] + match_score,  # Совпадение/замена
                score_matrix[i - 1][j] + gap,             # Пропуск в seq2
                score_matrix[i][j - 1] + gap              # Пропуск в seq1
            )

    # Обратный проход для восстановления выравнивания
    aligned_seq1 = []
    aligned_seq2 = []
    i, j = n, m

    while i > 0 and j > 0:
        current_score = score_matrix[i][j]
        match_score = match if seq1[i - 1] == seq2[j - 1] else mismatch

        if current_score == score_matrix[i - 1][j - 1] + match_score:
            aligned_seq1.append(seq1[i - 1])
            aligned_seq2.append(seq2[j - 1])
            i -= 1
            j -= 1
        elif current_score == score_matrix[i - 1][j] + gap:
            aligned_seq1.append(seq1[i - 1])
            aligned_seq2.append('-')
            i -= 1
        else:
            aligned_seq1.append('-')
            aligned_seq2.append(seq2[j - 1])
            j -= 1

    # Добавляем оставшиеся символы
    while i > 0:
        aligned_seq1.append(seq1[i - 1])
        aligned_seq2.append('-')
        i -= 1
    while j > 0:
        aligned_seq1.append('-')
        aligned_seq2.append(seq2[j - 1])
        j -= 1

    # Разворачиваем выравненные последовательности
    aligned_seq1 = ''.join(reversed(aligned_seq1))
    aligned_seq2 = ''.join(reversed(aligned_seq2))

    return aligned_seq1, aligned_seq2, score_matrix


In [23]:
# Пример использования
seq1 = "GCT"
seq2 = "GCA"
result = needleman_wunsch(seq1, seq2)
print("Выравнивание 1:", result[0])
print("Выравнивание 2:", result[1])
print(np.array(result[2]))


Выравнивание 1: -GCT
Выравнивание 2: ABC-
[[ 0 -1 -2 -3]
 [-1 -1 -2 -3]
 [-2 -2 -2 -1]
 [-3 -3 -3 -2]]
